apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer # IBM Cloud will automatically provision a public IP for this
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
